repos:
-   repo: https://github.com/mgedmin/check-python-versions
    rev: 0.22.1
    hooks:
    -   id: check-python-versions
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bugbear==22.7.1
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
    -   id: bandit
        args:
        - --skip
        - B101
