repos:
-   repo: https://github.com/mgedmin/check-python-versions
    rev: 0.20.0
    hooks:
    -   id: check-python-versions
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bugbear==22.7.1
-   repo: https://github.com/PyCQA/isort.git
    rev: v5.11.3
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args:
        - --skip
        - B101
-   repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 0.5.2
    hooks:
    -   id: tox-ini-fmt
